import type { NodeTemplate } from "../types/workflow-canvas";

export const nodeTemplates: NodeTemplate[] = [
  {
    type: "trigger",
    label: "手动触发",
    icon: "⚡",
    category: "trigger",
    description: "手动启动一段灵感流程",
    defaultConfig: {},
    runtime: { kind: "local", label: "手动触发" },
    inputs: [],
    outputs: ["开始"],
    color: "#967739",
  },
  {
    type: "note-create",
    label: "新增笔记",
    icon: "📝",
    category: "action",
    description: "在笔记模块中新建一条笔记",
    defaultConfig: { title: "", content: "" },
    runtime: { kind: "local", label: "笔记模块：新增笔记", action: "notes.create" },
    inputs: ["标题", "内容"],
    outputs: ["笔记ID"],
    color: "#2d6f63",
  },
  {
    type: "note-save",
    label: "保存笔记",
    icon: "💾",
    category: "action",
    description: "保存当前笔记标题、正文或置顶状态",
    defaultConfig: { noteId: "", title: "", content: "" },
    runtime: { kind: "local", label: "笔记模块：保存笔记", action: "notes.save" },
    inputs: ["笔记ID", "内容"],
    outputs: ["保存状态"],
    color: "#2d6f63",
  },
  {
    type: "note-delete",
    label: "删除笔记",
    icon: "🗑️",
    category: "action",
    description: "删除指定笔记",
    defaultConfig: { noteId: "" },
    runtime: { kind: "local", label: "笔记模块：删除笔记", action: "notes.delete" },
    inputs: ["笔记ID"],
    outputs: ["删除状态"],
    color: "#b45b42",
  },
  {
    type: "note-export",
    label: "导出 Markdown",
    icon: "⬇️",
    category: "action",
    description: "把当前笔记导出为 .md 文件",
    defaultConfig: { noteId: "" },
    runtime: { kind: "local", label: "笔记模块：导出 Markdown", action: "notes.export" },
    inputs: ["笔记ID"],
    outputs: ["文件"],
    color: "#315f9b",
  },
  {
    type: "notes-query",
    label: "检索笔记",
    icon: "📚",
    category: "data",
    description: "按关键词读取笔记标题和正文",
    defaultConfig: { query: "", limit: 5 },
    runtime: { kind: "local", label: "笔记模块：检索笔记", action: "notes.query" },
    inputs: ["关键词"],
    outputs: ["笔记列表", "摘录"],
    color: "#65706b",
  },
  {
    type: "chat-thread",
    label: "读取会话",
    icon: "💬",
    category: "data",
    description: "读取 AI 会话或联系人私聊上下文",
    defaultConfig: { mode: "active_thread", limit: 20 },
    runtime: { kind: "api", label: "聊天模块：读取会话", method: "GET", path: "/api/chat/direct/:user_id" },
    inputs: ["联系人", "关键词"],
    outputs: ["消息列表", "会话摘要"],
    color: "#315f9b",
  },
  {
    type: "send-message",
    label: "发送消息",
    icon: "✉️",
    category: "action",
    description: "给指定联系人发送文字消息",
    defaultConfig: { recipient: "", message: "" },
    runtime: { kind: "api", label: "聊天模块：发送消息", method: "POST", path: "/api/chat/direct/:user_id" },
    inputs: ["联系人", "消息内容"],
    outputs: ["发送状态", "消息ID"],
    color: "#b45b42",
  },
  {
    type: "send-attachment",
    label: "发送附件",
    icon: "📎",
    category: "action",
    description: "给指定联系人发送图片或文件附件",
    defaultConfig: { recipient: "", files: [] },
    runtime: { kind: "api", label: "聊天模块：发送附件", method: "POST", path: "/api/chat/direct/:user_id" },
    inputs: ["联系人", "附件", "说明"],
    outputs: ["发送状态", "消息ID"],
    color: "#b45b42",
  },
  {
    type: "ai-chat",
    label: "AI 对话",
    icon: "🤖",
    category: "action",
    description: "使用交耳里的当前 AI 联系人生成回复",
    defaultConfig: { prompt: "", model: "", temperature: 0.7 },
    runtime: { kind: "api", label: "聊天模块：AI 对话", method: "POST", path: "/api/chat" },
    inputs: ["输入", "上下文"],
    outputs: ["回复"],
    color: "#2d6f63",
  },
  {
    type: "provider-models",
    label: "获取模型列表",
    icon: "🔌",
    category: "action",
    description: "读取中枢当前 API 支持的模型列表",
    defaultConfig: { provider: "openai", baseUrl: "" },
    runtime: { kind: "api", label: "中枢：获取模型列表", method: "POST", path: "/api/catalog/provider/models" },
    inputs: ["API配置"],
    outputs: ["模型列表", "选中模型"],
    color: "#2d6f63",
  },
  {
    type: "api-health",
    label: "测试模型接口",
    icon: "🩺",
    category: "action",
    description: "测试中枢 API Key、Base URL 和模型是否可用",
    defaultConfig: { provider: "openai", timeoutSeconds: 20 },
    runtime: { kind: "api", label: "中枢：测试模型接口", method: "POST", path: "/api/catalog/provider/test" },
    inputs: ["API配置"],
    outputs: ["状态", "延迟", "错误"],
    color: "#2d6f63",
  },
  {
    type: "image-gen",
    label: "生成图片",
    icon: "🎨",
    category: "action",
    description: "调用虚实模块生成图片",
    defaultConfig: { prompt: "", size: "1024x1024", quality: "standard" },
    runtime: { kind: "api", label: "虚实：生成图片", method: "POST", path: "/api/images/generate" },
    inputs: ["提示词"],
    outputs: ["图片", "修订提示词"],
    color: "#315f9b",
  },
  {
    type: "memory-map",
    label: "地图记忆",
    icon: "🗺️",
    category: "data",
    description: "读取或整理地图纪念里的城市、地点和游记",
    defaultConfig: { city: "", query: "" },
    runtime: { kind: "api", label: "地图：城市搜索", method: "GET", path: "/api/maps/tencent/city-search" },
    inputs: ["城市", "记忆"],
    outputs: ["地点", "记忆卡片"],
    color: "#65706b",
  },
  {
    type: "token-usage",
    label: "Token 统计",
    icon: "📈",
    category: "data",
    description: "读取 Token 统计概览、趋势或排行榜",
    defaultConfig: { range: "30d", view: "overview" },
    runtime: { kind: "api", label: "Token 统计：读取概览", method: "GET", path: "/api/token-usage/dashboard" },
    inputs: ["范围"],
    outputs: ["概览", "趋势", "排行"],
    color: "#315f9b",
  },
  {
    type: "agent-run",
    label: "送入秩序",
    icon: "🧭",
    category: "action",
    description: "把当前流程交给秩序模块执行或复核",
    defaultConfig: { agentId: "workflow-agent", mcpServers: [] },
    runtime: { kind: "api", label: "秩序：运行流程", method: "POST", path: "/api/agents/runs" },
    inputs: ["任务", "上下文"],
    outputs: ["运行ID", "摘要", "状态"],
    color: "#b45b42",
  },
];

export function getNodeTemplate(type: string): NodeTemplate | undefined {
  return nodeTemplates.find((t) => t.type === type);
}

export function getNodesByCategory(category: string): NodeTemplate[] {
  return nodeTemplates.filter((t) => t.category === category);
}
