import type { NodeTemplate } from "../types/workflow-canvas";

export const nodeTemplates: NodeTemplate[] = [
  // 触发器类
  {
    type: "trigger",
    label: "手动触发",
    icon: "⚡",
    category: "trigger",
    description: "手动启动工作流",
    defaultConfig: {},
    inputs: [],
    outputs: ["output"],
    color: "#967739",
  },
  {
    type: "workflow-trigger",
    label: "定时触发",
    icon: "⏰",
    category: "trigger",
    description: "按计划自动执行",
    defaultConfig: { schedule: "0 9 * * *" },
    inputs: [],
    outputs: ["output"],
    color: "#967739",
  },

  // AI 动作类
  {
    type: "ai-chat",
    label: "AI 对话",
    icon: "🤖",
    category: "action",
    description: "调用 AI 模型生成回复",
    defaultConfig: {
      prompt: "",
      model: "",
      temperature: 0.7,
    },
    inputs: ["input", "context"],
    outputs: ["response", "tokens"],
    color: "#2d6f63",
  },
  {
    type: "image-gen",
    label: "生成图片",
    icon: "🎨",
    category: "action",
    description: "使用 AI 生成图片",
    defaultConfig: {
      prompt: "",
      size: "1024x1024",
      quality: "standard",
    },
    inputs: ["prompt"],
    outputs: ["image_url", "revised_prompt"],
    color: "#315f9b",
  },

  // 消息动作类
  {
    type: "send-message",
    label: "发送消息",
    icon: "💬",
    category: "action",
    description: "发送消息给指定用户",
    defaultConfig: {
      recipient: "",
      message: "",
    },
    inputs: ["recipient", "content", "attachments"],
    outputs: ["success", "message_id"],
    color: "#b45b42",
  },

  // HTTP 请求
  {
    type: "http-request",
    label: "HTTP 请求",
    icon: "🌐",
    category: "action",
    description: "发送 HTTP 请求",
    defaultConfig: {
      method: "GET",
      url: "",
      headers: {},
      body: "",
    },
    inputs: ["url", "params"],
    outputs: ["response", "status", "error"],
    color: "#65706b",
  },
  {
    type: "provider-models",
    label: "获取模型列表",
    icon: "🔌",
    category: "action",
    description: "读取接口中枢当前 API 支持的模型",
    defaultConfig: {
      provider: "openai",
      baseUrl: "",
    },
    inputs: ["api_config"],
    outputs: ["models", "selected_model"],
    color: "#2d6f63",
  },
  {
    type: "api-health",
    label: "接口健康检查",
    icon: "🩺",
    category: "action",
    description: "检查接口中枢的密钥、Base URL、模型端点和延迟状态",
    defaultConfig: {
      provider: "openai",
      timeoutSeconds: 20,
    },
    inputs: ["api_config"],
    outputs: ["status", "latency", "error"],
    color: "#2d6f63",
  },
  {
    type: "webhook-ingress",
    label: "Webhook 入口",
    icon: "📡",
    category: "trigger",
    description: "接收外部系统事件并转成秩序任务输入",
    defaultConfig: {
      path: "/webhooks/workflow",
      method: "POST",
    },
    inputs: [],
    outputs: ["payload", "headers"],
    color: "#967739",
  },
  {
    type: "token-usage",
    label: "Token 统计",
    icon: "📈",
    category: "data",
    description: "读取 Token 统计概览、趋势或排行数据",
    defaultConfig: {
      range: "30d",
      view: "overview",
    },
    inputs: ["range"],
    outputs: ["overview", "trend", "rankings"],
    color: "#315f9b",
  },
  {
    type: "chat-thread",
    label: "会话线程",
    icon: "💬",
    category: "data",
    description: "读取交耳里的 AI 或联系人会话上下文",
    defaultConfig: {
      mode: "active_thread",
      limit: 20,
    },
    inputs: ["query", "user"],
    outputs: ["messages", "summary"],
    color: "#315f9b",
  },
  {
    type: "contact-profile",
    label: "联系人档案",
    icon: "👤",
    category: "data",
    description: "读取联系人、群组或客户上下文，供消息和秩序流程使用",
    defaultConfig: {
      scope: "active_contact",
      includeHistory: true,
    },
    inputs: ["contact", "query"],
    outputs: ["profile", "preferences"],
    color: "#315f9b",
  },
  {
    type: "calendar-event",
    label: "日程事件",
    icon: "📅",
    category: "data",
    description: "读取或准备日程、提醒和时间窗口",
    defaultConfig: {
      range: "7d",
      includeTasks: true,
    },
    inputs: ["time_range", "query"],
    outputs: ["events", "availability"],
    color: "#967739",
  },
  {
    type: "notification-send",
    label: "通知发送",
    icon: "🔔",
    category: "action",
    description: "把秩序结果发送到站内提醒、聊天或外部通知通道",
    defaultConfig: {
      channel: "in_app",
      requireReview: true,
    },
    inputs: ["recipient", "content"],
    outputs: ["delivery", "status"],
    color: "#b45b42",
  },
  {
    type: "database-query",
    label: "数据库查询",
    icon: "🗄️",
    category: "data",
    description: "读取系统数据库里的结构化记录，作为流程上下文",
    defaultConfig: {
      table: "",
      limit: 20,
    },
    inputs: ["query", "filters"],
    outputs: ["rows", "schema"],
    color: "#65706b",
  },
  {
    type: "image-studio",
    label: "绘影接口",
    icon: "🖼️",
    category: "action",
    description: "把提示词送入绘影生成图片或读取最近图片结果",
    defaultConfig: {
      size: "1024x1024",
      count: 1,
    },
    inputs: ["prompt", "style"],
    outputs: ["image_url", "metadata"],
    color: "#315f9b",
  },
  {
    type: "notes-query",
    label: "笔记检索",
    icon: "📚",
    category: "data",
    description: "从笔记模块读取标题、正文或标签线索",
    defaultConfig: {
      query: "",
      limit: 5,
    },
    inputs: ["query"],
    outputs: ["notes", "excerpt"],
    color: "#65706b",
  },
  {
    type: "knowledge-search",
    label: "知识检索",
    icon: "🔎",
    category: "data",
    description: "在系统知识库、文档和历史输出中检索上下文",
    defaultConfig: {
      query: "",
      topK: 8,
    },
    inputs: ["query", "filters"],
    outputs: ["documents", "citations"],
    color: "#65706b",
  },
  {
    type: "file-asset",
    label: "文件资产",
    icon: "📎",
    category: "data",
    description: "读取上传文件、图片结果或导出文档作为流程输入",
    defaultConfig: {
      source: "latest",
      limit: 5,
    },
    inputs: ["query"],
    outputs: ["files", "metadata"],
    color: "#315f9b",
  },
  {
    type: "email-inbox",
    label: "邮件收件箱",
    icon: "✉️",
    category: "data",
    description: "读取邮箱、表单通知或外部来信，转成流程上下文",
    defaultConfig: {
      folder: "inbox",
      limit: 10,
      unreadOnly: true,
    },
    inputs: ["query", "sender"],
    outputs: ["messages", "attachments"],
    color: "#315f9b",
  },
  {
    type: "cloud-drive",
    label: "云盘文件",
    icon: "☁️",
    category: "data",
    description: "读取云盘目录、共享文件和最近文档",
    defaultConfig: {
      provider: "system",
      folder: "",
      limit: 8,
    },
    inputs: ["query", "folder"],
    outputs: ["files", "links"],
    color: "#65706b",
  },
  {
    type: "sheet-row",
    label: "表格数据",
    icon: "▦",
    category: "data",
    description: "读取表格行、筛选结果或运营数据",
    defaultConfig: {
      sheet: "",
      range: "A:Z",
      limit: 50,
    },
    inputs: ["sheet", "filter"],
    outputs: ["rows", "summary"],
    color: "#65706b",
  },
  {
    type: "module-catalog",
    label: "系统模块",
    icon: "🧩",
    category: "data",
    description: "读取当前可用模块、入口和模块启用状态",
    defaultConfig: {
      includeDisabled: false,
    },
    inputs: ["filter"],
    outputs: ["modules", "routes"],
    color: "#65706b",
  },
  {
    type: "mcp-tool",
    label: "MCP 工具",
    icon: "🛠️",
    category: "action",
    description: "选择秩序模块可用 MCP Server 和工具执行",
    defaultConfig: {
      serverId: "bigmodel-web-search",
      toolName: "webSearchPrime",
    },
    inputs: ["arguments", "context"],
    outputs: ["result", "status"],
    color: "#2d6f63",
  },
  {
    type: "admin-audit",
    label: "管理审计",
    icon: "🛡️",
    category: "data",
    description: "读取管理员端策略、模块开关和执行审计线索",
    defaultConfig: {
      scope: "workflow",
    },
    inputs: ["run_id", "scope"],
    outputs: ["policy", "audit"],
    color: "#967739",
  },
  {
    type: "cms-publish",
    label: "内容发布",
    icon: "📣",
    category: "action",
    description: "把秩序结果发布到内容系统，默认需要人工复核",
    defaultConfig: {
      channel: "draft",
      requireReview: true,
    },
    inputs: ["title", "content", "assets"],
    outputs: ["draft_id", "status"],
    color: "#b45b42",
  },
  {
    type: "memory-map",
    label: "地图记忆",
    icon: "🗺️",
    category: "data",
    description: "读取或写入城市、地点和记忆线索",
    defaultConfig: {
      city: "",
      query: "",
    },
    inputs: ["city", "memory"],
    outputs: ["places", "memory_card"],
    color: "#65706b",
  },
  {
    type: "agent-run",
    label: "秩序 Agent",
    icon: "🧭",
    category: "action",
    description: "把当前内容交给秩序模块的 Agent / MCP 流程",
    defaultConfig: {
      agentId: "researcher",
      mcpServers: [],
    },
    inputs: ["task", "context"],
    outputs: ["run_id", "summary", "status"],
    color: "#b45b42",
  },

  // 逻辑控制
  {
    type: "condition",
    label: "条件判断",
    icon: "🔀",
    category: "logic",
    description: "根据条件分支执行",
    defaultConfig: {
      condition: "",
      operator: "equals",
    },
    inputs: ["input"],
    outputs: ["true", "false"],
    color: "#967739",
  },
  {
    type: "loop",
    label: "循环",
    icon: "🔁",
    category: "logic",
    description: "遍历数组或重复执行",
    defaultConfig: {
      items: [],
      maxIterations: 100,
    },
    inputs: ["items"],
    outputs: ["item", "index", "done"],
    color: "#967739",
  },
  {
    type: "delay",
    label: "延迟",
    icon: "⏱️",
    category: "logic",
    description: "等待指定时间",
    defaultConfig: {
      duration: 1000,
      unit: "ms",
    },
    inputs: ["input"],
    outputs: ["output"],
    color: "#967739",
  },

  // 数据处理
  {
    type: "transform",
    label: "数据转换",
    icon: "🔧",
    category: "data",
    description: "转换或处理数据",
    defaultConfig: {
      script: "return input;",
    },
    inputs: ["input"],
    outputs: ["output"],
    color: "#65706b",
  },
  {
    type: "note-create",
    label: "创建笔记",
    icon: "📝",
    category: "action",
    description: "保存内容到笔记",
    defaultConfig: {
      title: "",
      content: "",
    },
    inputs: ["title", "content"],
    outputs: ["note_id"],
    color: "#2d6f63",
  },
];

export function getNodeTemplate(type: string): NodeTemplate | undefined {
  return nodeTemplates.find((t) => t.type === type);
}

export function getNodesByCategory(category: string): NodeTemplate[] {
  return nodeTemplates.filter((t) => t.category === category);
}
